package com.impacto.idocx.command.exceptions;

import lombok.Getter;

@Getter
public enum ErrorCode {
    USER_NOT_FOUND_EXCEPTION(1),
    FILE_NOT_FOUND_EXCEPTION(2),
    DIRECTORY_EXCEPTION(3),
    STORAGE_INITIALIZATION_EXCEPTION(4),
    FILE_READING_EXCEPTION(5),
    FOLDER_ALREADY_EXISTS_EXCEPTION(6),
    FILE_STORAGE_EXCEPTION(7),
    UNSUPPORTED_EXCEPTION(8),
    RESOURCE_NOT_FOUND_EXCEPTION(9),
    FAILED_TO_DELETE_RESOURCE_EXCEPTION(10),
    FAILED_TO_UPDATE_FILE_EXCEPTION(11),
    FAILED_TO_UPDATE_FOLDER_EXCEPTION(12),
    FAILED_TO_COMPRESS_RESOURCE_EXCEPTION(13),
    INVALID_EXCEL_FORMAT_EXCEPTION(14),
    LIMIT_EXCEEDING_EXCEPTION(15);

    private final int code;

    ErrorCode(int code) {
        this.code = code;
    }

}
